apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom-app-backend 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boom-app-backend
      tier: backend
  template:
    metadata:
      labels:
        app: boom-app-backend
        tier: backend  # Add tier label for the backend
    spec:
      containers:
      - name: lendsqr-backend
        image: ghcr.io/shawen17/boom-app-job-lendsqr_backend:122
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: ${DB_USER}
        - name: PASSWORD
          value: ${PASSWORD}
        - name: CLUSTERNAME
          value: ${CLUSTERNAME}
        - name: REDIS
          value: redis-service
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom-app-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boom-app-frontend
      tier: frontend
  template:
    metadata:
      labels:
        app: boom-app-frontend
        tier: frontend  
    spec:
      containers:
      - name: lendsqr-frontend
        image: ghcr.io/shawen17/boom-app-job-lendsqr:122
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_LENDSQR_API_URL
          value: "https://backend.dashme.ng"  
        - name: REACT_APP_MEDIA_URL
          value: ${REACT_APP_MEDIA_URL}
      imagePullSecrets:
      - name: ghcr-secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      tier: cache
  template:
    metadata:
      labels:
        app: redis
        tier: cache  
    spec:
      containers:
      - name: redis-cache
        image: redis
        ports:
        - containerPort: 6379
        
      