apiVersion: apps/v1
kind: Deployment
metadata:
  name: boom-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: boom-app
  template:
    metadata:
      labels:
        app: boom-app
    spec:
      containers:
      - name: lendsqr-backend
        image: ${LENDSQR_BACKEND_IMAGE}
        ports:
        - containerPort: 8000
        env:
        - name: DB_USER
          value: ${DB_USER}
        - name: PASSWORD
          value: ${PASSWORD}
        - name: CLUSTERNAME
          value: ${CLUSTERNAME}
      - name: lendsqr-frontend
        image: ${LENDSQR_IMAGE}
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_LENDSQR_API_URL
          value: "http://boom-app-backend-service:8000"
        - name: REACT_APP_MEDIA_URL
          value: ${REACT_APP_MEDIA_URL}
      imagePullSecrets:
      - name: ghcr-secret
