version: "3.8"

services:
  lendsqr_backend:
    image: ${LENDSQR_BACKEND_IMAGE}
    container_name: "lendsqr_backend${TAG}"
    ports:
      - 8000:8000
    restart: always
    environment:
      DB_USER: ${DB_USER}
      PASSWORD: ${PASSWORD}
      CLUSTERNAME: ${CLUSTERNAME}
      

  lendsqr:
    image: ${LENDSQR_IMAGE}
    container_name: "lendsqr${TAG}"
    ports:
      - 3000:3000
    environment:
      REACT_APP_LENDSQR_API_URL: ${REACT_APP_LENDSQR_API_URL}
      REACT_APP_MEDIA_URL: ${REACT_APP_MEDIA_URL}

