version: "3.8"

services:
  lendsqr_backend:
    build:
      context: ./lendsqr_backend
      dockerfile: Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}

  lendsqr:
    build:
      context: ./lendsqr
      dockerfile: Dockerfile
