version: "3.8"

services:
  lendsqr_backend:
    image: ${IMAGE_NAME}-lendsqr_backend:latest
    container_name: lendsqr_backend
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    restart: always
    volumes:
      - ./lendsqr_backend/lendsqr/:/app/lendsqr
      - ./lendsqr_backend:/app
      - ./lendsqr_backend/media:/app/media

  lendsqr:
    image: ${IMAGE_NAME}-lendsqr:latest
    command: yarn start 0.0.0.0:3000
    ports:
      - 3000:3000
    volumes:
      - ./lendsqr:/app
      - ./lendsqr/node_modules:/app/node_modules
      - ./lendsqr/public:/app/public
