version: "3.8"

services:
  lendsqr_backend:
    build:
      context: ./lendsqr_backend
      dockerfile: Dockerfile
      args:
        - SECRET_KEY=${SECRET_KEY}
        - HOST=${HOST}
        - AUTH_PASSWORD=${AUTH_PASSWORD}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}


  lendsqr:
    build:
      context: ./lendsqr
      dockerfile: Dockerfile
