apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: boom-app-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  rules:
    - host: www.dashme.ng
      http:
        paths:
          - path: /frontend
            pathType: Prefix
            backend:
              service:
                name: boom-app-frontend-service
                port:
                  number: 80
          - path: /backend
            pathType: Prefix
            backend:
              service:
                name: boom-app-backend-service
                port:
                  number: 80
  tls:
    - hosts:
        - www.dashme.ng
      secretName: my-tls-secret  # Name of the TLS secret for the domain
