global:
  scrape_interval: 15s # Set the interval at which Prometheus will scrape the targets

scrape_configs:
  - job_name: 'lendsqr_backend'
    static_configs:
      - targets: ['localhost:8000']
    relabel_configs:
      - source_labels: [__address__] 
        regex: "([^:]+):\\d+"
        target_label: instance

  - job_name: 'lendsqr'
    static_configs:
      - targets: ['metrics-server:3002']

  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
