apiVersion: v1
kind: Service
metadata:
  name: boom-app-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: boom-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Frontend container port
---
apiVersion: v1
kind: Service
metadata:
  name: boom-app-backend-service
spec:
  type: ClusterIP
  selector:
    app: boom-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000  # Backend container port
