apiVersion: v1
kind: Service
metadata:
  name: boom-app-frontend-service
spec:
  type: LoadBalancer
  selector:
    app: boom-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000  # Frontend container port
---
apiVersion: v1
kind: Service
metadata:
  name: boom-app-backend-service
spec:
  type: LoadBalancer  # Change this to LoadBalancer to expose the backend to the internet
  selector:
    app: boom-app
    tier: backend  # Add tier selector for the backend
  ports:
    - protocol: TCP
      port: 80  # Expose port 80 to the internet
      targetPort: 8000  # Backend container port
