body = [
    {
        "totalDocuments": 113,
        "totalActive": 34,
        "totalWithLoan": 103,
        "totalWithSavings": 104,
        "documents": [
            {
                "_id": "65c7fe3ffe207b9decf40ad8",
                "profile": {
                    "firstName": "Lia",
                    "lastName": "Wolf",
                    "phoneNumber": "769-700-5119",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/26.jpg",
                    "gender": "Male",
                    "bvn": "283370324",
                    "address": "Cayla Highway",
                    "currency": "NGN",
                    "email": "Everett.Lindgren@yahoo.com",
                    "userName": "Beaulah0",
                    "status": "Active",
                },
                "guarantor": {
                    "guaAddress": "Hagenes Pine",
                    "guaFirstName": "Griffin",
                    "guaGender": "Male",
                    "guaLastName": "Hahn",
                    "guaNumber": "911.728.0682",
                    "relationship": "Uncle",
                },
                "account": {
                    "accountName": "4B3PP9G3Q2",
                    "accountBalance": 37635.65,
                    "loanRepayment": 199066.81,
                    "monthlyIncome": [49858.49, 2911196.22],
                    "bank": "Stanbic IBTC",
                    "accountNumber": 8945563245,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "et-unde-adipisci",
                    "orgNumber": "(638) 379-0317",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Joy82@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ad9",
                "profile": {
                    "firstName": "Casper",
                    "lastName": "Hackett",
                    "phoneNumber": "224-499-8144 x64664",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/272.jpg",
                    "gender": "Male",
                    "bvn": "775033030",
                    "address": "Ruby Via",
                    "currency": "NGN",
                    "email": "Kaela.Powlowski14@hotmail.com",
                    "userName": "Dalton_Rogahn",
                    "status": "Inactive",
                },
                "guarantor": {
                    "guaAddress": "Roberta View",
                    "guaFirstName": "Frida",
                    "guaGender": "Male",
                    "guaLastName": "Larson",
                    "guaNumber": "(664) 657-3686 x828",
                    "relationship": "Daughter",
                },
                "account": {
                    "accountName": "TWIT16ZZOB",
                    "accountBalance": 97134.29,
                    "loanRepayment": 83354.04,
                    "monthlyIncome": [52333.12, 245389.17],
                    "bank": "Heritage",
                    "accountNumber": 3205796378,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "et-error-perspiciatis",
                    "orgNumber": "761.572.9104 x6215",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Tommie.Lind@hotmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ada",
                "profile": {
                    "firstName": "Sammie",
                    "lastName": "Olson",
                    "phoneNumber": "212-802-0920 x0721",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/640.jpg",
                    "gender": "Male",
                    "bvn": "124157981",
                    "address": "Maggio Oval",
                    "currency": "NGN",
                    "email": "Zack_Ebert42@yahoo.com",
                    "userName": "Kyler20",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Monique Mountain",
                    "guaFirstName": "Kaia",
                    "guaGender": "Male",
                    "guaLastName": "MacGyver",
                    "guaNumber": "892.269.2260",
                    "relationship": "Daughter",
                },
                "account": {
                    "accountName": "DZFIG28XKQ",
                    "accountBalance": 83001.83,
                    "loanRepayment": 76589.65,
                    "monthlyIncome": [66904.23, 2438288.14],
                    "bank": "UBA",
                    "accountNumber": 4903826453,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "cum-aliquam-aut",
                    "orgNumber": "533.215.6201",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Marc.Rippin50@hotmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40adb",
                "profile": {
                    "firstName": "Jamarcus",
                    "lastName": "Ruecker",
                    "phoneNumber": "440.453.2875",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/479.jpg",
                    "gender": "Male",
                    "bvn": "631096470",
                    "address": "Maia Meadows",
                    "currency": "NGN",
                    "email": "Jaleel_Runolfsson41@yahoo.com",
                    "userName": "Jadon_McKenzie",
                    "status": "Blacklisted",
                },
                "guarantor": {
                    "guaAddress": "Candice Streets",
                    "guaFirstName": "Buford",
                    "guaGender": "Male",
                    "guaLastName": "Farrell",
                    "guaNumber": "(710) 520-4502 x168",
                    "relationship": "Aunty",
                },
                "account": {
                    "accountName": "6W74VQ2RMB",
                    "accountBalance": 54442.73,
                    "loanRepayment": 86646.03,
                    "monthlyIncome": [69296.36, 193217.07],
                    "bank": "First Bank",
                    "accountNumber": 9570032589,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "consequuntur-expedita-nihil",
                    "orgNumber": "1-524-368-8038",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Jaydon.Jerde@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40adc",
                "profile": {
                    "firstName": "Johathan",
                    "lastName": "Schmidt",
                    "phoneNumber": "698.938.8298",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/921.jpg",
                    "gender": "Male",
                    "bvn": "655829940",
                    "address": "Williamson Parkways",
                    "currency": "NGN",
                    "email": "Deangelo58@gmail.com",
                    "userName": "Toby.Stroman83",
                    "status": "Inactive",
                },
                "guarantor": {
                    "guaAddress": "Dayna Trace",
                    "guaFirstName": "Lew",
                    "guaGender": "Male",
                    "guaLastName": "Walter",
                    "guaNumber": "(608) 497-1195",
                    "relationship": "Uncle",
                },
                "account": {
                    "accountName": "KOC3LR7DHC",
                    "accountBalance": 35146.87,
                    "loanRepayment": 89706.29,
                    "monthlyIncome": [56589.39, 499507.13],
                    "bank": "Fidelity",
                    "accountNumber": 1637648590,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "ut-consequatur-quaerat",
                    "orgNumber": "(345) 929-0703 x80670",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Rafaela_Littel@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40add",
                "profile": {
                    "firstName": "Annabel",
                    "lastName": "Bechtelar",
                    "phoneNumber": "422.628.3585 x7611",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/399.jpg",
                    "gender": "Male",
                    "bvn": "523905624",
                    "address": "Becker Loop",
                    "currency": "NGN",
                    "email": "Jarrett.Fahey@yahoo.com",
                    "userName": "Sedrick.Gutkowski51",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Maybell Route",
                    "guaFirstName": "Thelma",
                    "guaGender": "Male",
                    "guaLastName": "Koch",
                    "guaNumber": "560.626.1802 x1933",
                    "relationship": "Sibling",
                },
                "account": {
                    "accountName": "OUAC0KNCMJ",
                    "accountBalance": 98735.2,
                    "loanRepayment": 33704.46,
                    "monthlyIncome": [78575.73, 1594855.94],
                    "bank": "GTB",
                    "accountNumber": 3379863953,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "soluta-unde-totam",
                    "orgNumber": "492-311-2606 x19746",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Savannah4@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ade",
                "profile": {
                    "firstName": "Herman",
                    "lastName": "O'Keefe",
                    "phoneNumber": "1-491-225-3542 x41555",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/401.jpg",
                    "gender": "Male",
                    "bvn": "449422906",
                    "address": "Sawayn Glens",
                    "currency": "NGN",
                    "email": "Raul.Hirthe@hotmail.com",
                    "userName": "Einar.Crist",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Prohaska Parkway",
                    "guaFirstName": "Freda",
                    "guaGender": "Male",
                    "guaLastName": "Lynch",
                    "guaNumber": "1-723-333-3195 x68018",
                    "relationship": "Sibling",
                },
                "account": {
                    "accountName": "LIDQF8FFMH",
                    "accountBalance": 63821.51,
                    "loanRepayment": 80508.35,
                    "monthlyIncome": [76239.4, 1506135.65],
                    "bank": "Fidelity",
                    "accountNumber": 9538095183,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "quod-totam-voluptatibus",
                    "orgNumber": "539.476.4467 x7580",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Lura.Leffler50@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40adf",
                "profile": {
                    "firstName": "Rylee",
                    "lastName": "Howell",
                    "phoneNumber": "917.251.9209",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/498.jpg",
                    "gender": "Male",
                    "bvn": "860961677",
                    "address": "Wiegand Glens",
                    "currency": "NGN",
                    "email": "Kristin51@gmail.com",
                    "userName": "Madisyn22",
                    "status": "Active",
                },
                "guarantor": {
                    "guaAddress": "Gislason Trace",
                    "guaFirstName": "Amanda",
                    "guaGender": "Male",
                    "guaLastName": "O'Connell",
                    "guaNumber": "1-766-389-7750",
                    "relationship": "Sibling",
                },
                "account": {
                    "accountName": "SGARYV1O1X",
                    "accountBalance": 77045.63,
                    "loanRepayment": 183672.78,
                    "monthlyIncome": [39875.84, 2993028.01],
                    "bank": "Stanbic IBTC",
                    "accountNumber": 2810552480,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "deleniti-ut-et",
                    "orgNumber": "(760) 687-5492",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Nick.Swaniawski@hotmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae0",
                "profile": {
                    "firstName": "Jadyn",
                    "lastName": "King",
                    "phoneNumber": "772-867-5409 x8215",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1057.jpg",
                    "gender": "Male",
                    "bvn": "784496914",
                    "address": "Kertzmann Branch",
                    "currency": "NGN",
                    "email": "Madaline_Hauck35@yahoo.com",
                    "userName": "Rebekah_Pfeffer12",
                    "status": "Blacklisted",
                },
                "guarantor": {
                    "guaAddress": "Bergnaum River",
                    "guaFirstName": "Cordie",
                    "guaGender": "Male",
                    "guaLastName": "O'Kon",
                    "guaNumber": "1-978-897-0416 x988",
                    "relationship": "Son",
                },
                "account": {
                    "accountName": "0RGMORG73C",
                    "accountBalance": 48121.04,
                    "loanRepayment": 31232.63,
                    "monthlyIncome": [54132.52, 2101848.38],
                    "bank": "Parallex",
                    "accountNumber": 4434155458,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "voluptatem-repellendus-aut",
                    "orgNumber": "1-325-504-7986 x5167",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Wanda.Aufderhar@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae1",
                "profile": {
                    "firstName": "Sigrid",
                    "lastName": "Kunze",
                    "phoneNumber": "964-565-4763",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/56.jpg",
                    "gender": "Male",
                    "bvn": "470263231",
                    "address": "Bernhard Ways",
                    "currency": "NGN",
                    "email": "Hannah50@gmail.com",
                    "userName": "Marcellus91",
                    "status": "Active",
                },
                "guarantor": {
                    "guaAddress": "Ignatius Orchard",
                    "guaFirstName": "Maude",
                    "guaGender": "Male",
                    "guaLastName": "Rolfson",
                    "guaNumber": "314-955-4114",
                    "relationship": "Son",
                },
                "account": {
                    "accountName": "FLCS0NWMFE",
                    "accountBalance": 53462.22,
                    "loanRepayment": 193548.3,
                    "monthlyIncome": [68377.23, 2611543.57],
                    "bank": "Globus",
                    "accountNumber": 3529323715,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "ipsam-illo-tenetur",
                    "orgNumber": "1-684-619-0562",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Carolina.Daniel@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae2",
                "profile": {
                    "firstName": "Alf",
                    "lastName": "Powlowski",
                    "phoneNumber": "566.652.0915 x5676",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/717.jpg",
                    "gender": "Male",
                    "bvn": "530587200",
                    "address": "Armani Bridge",
                    "currency": "NGN",
                    "email": "Cristina.McGlynn82@gmail.com",
                    "userName": "Marvin_Bernier54",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Keira Trace",
                    "guaFirstName": "Marge",
                    "guaGender": "Male",
                    "guaLastName": "Welch",
                    "guaNumber": "423.252.1194 x2816",
                    "relationship": "Parent",
                },
                "account": {
                    "accountName": "2BUJDI4UFI",
                    "accountBalance": 41507.56,
                    "loanRepayment": 48103.29,
                    "monthlyIncome": [61859.84, 2998948.75],
                    "bank": "UBA",
                    "accountNumber": 4122641395,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "sit-ab-commodi",
                    "orgNumber": "(634) 836-6097",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Nichole.Gottlieb@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae3",
                "profile": {
                    "firstName": "Mohammed",
                    "lastName": "Schultz",
                    "phoneNumber": "1-275-210-1127 x782",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1084.jpg",
                    "gender": "Male",
                    "bvn": "392209182",
                    "address": "Adams Roads",
                    "currency": "NGN",
                    "email": "Michale.Morissette67@yahoo.com",
                    "userName": "Victor.Sawayn31",
                    "status": "Active",
                },
                "guarantor": {
                    "guaAddress": "Benedict Via",
                    "guaFirstName": "Violette",
                    "guaGender": "Male",
                    "guaLastName": "Dare",
                    "guaNumber": "592.840.6316",
                    "relationship": "Spouse",
                },
                "account": {
                    "accountName": "SBG0XO9KBX",
                    "accountBalance": 48045.81,
                    "loanRepayment": 192626.04,
                    "monthlyIncome": [36323.56, 392327.85],
                    "bank": "Access",
                    "accountNumber": 3712552897,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "dignissimos-nihil-voluptas",
                    "orgNumber": "1-824-504-1857",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Montana_OKon69@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae4",
                "profile": {
                    "firstName": "Joanie",
                    "lastName": "Goodwin",
                    "phoneNumber": "278.835.4759",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/874.jpg",
                    "gender": "Male",
                    "bvn": "822151661",
                    "address": "Alicia Rue",
                    "currency": "NGN",
                    "email": "Demetrius.Cronin@yahoo.com",
                    "userName": "Ayana26",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Vaughn Freeway",
                    "guaFirstName": "Albert",
                    "guaGender": "Male",
                    "guaLastName": "Grant",
                    "guaNumber": "297.871.8514",
                    "relationship": "Parent",
                },
                "account": {
                    "accountName": "EH4SA8280Y",
                    "accountBalance": 69321.7,
                    "loanRepayment": 84641.5,
                    "monthlyIncome": [62740.45, 607430.21],
                    "bank": "Polaris",
                    "accountNumber": 6396734751,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "et-ullam-repellat",
                    "orgNumber": "269.299.6060 x04771",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "William_Terry@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae5",
                "profile": {
                    "firstName": "Frederick",
                    "lastName": "Rempel",
                    "phoneNumber": "(845) 700-7417",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/951.jpg",
                    "gender": "Male",
                    "bvn": "807156393",
                    "address": "Jacobs Centers",
                    "currency": "NGN",
                    "email": "Vern20@gmail.com",
                    "userName": "Shannon.Parker",
                    "status": "Active",
                },
                "guarantor": {
                    "guaAddress": "Spinka Extensions",
                    "guaFirstName": "Mateo",
                    "guaGender": "Male",
                    "guaLastName": "Lueilwitz",
                    "guaNumber": "824-350-3667",
                    "relationship": "Cousin",
                },
                "account": {
                    "accountName": "4YBJDOA8Z9",
                    "accountBalance": 40085.0,
                    "loanRepayment": 64310.81,
                    "monthlyIncome": [65781.89, 1207289.27],
                    "bank": "Heritage",
                    "accountNumber": 2317466002,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "repellat-impedit-rem",
                    "orgNumber": "267-387-6785 x56967",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Jody_Sporer@hotmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae6",
                "profile": {
                    "firstName": "Dixie",
                    "lastName": "Anderson",
                    "phoneNumber": "1-917-259-8129",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/637.jpg",
                    "gender": "Male",
                    "bvn": "040939306",
                    "address": "Esmeralda Park",
                    "currency": "NGN",
                    "email": "Randall_Muller@yahoo.com",
                    "userName": "Elvis_Block39",
                    "status": "Pending",
                },
                "guarantor": {
                    "guaAddress": "Harley Field",
                    "guaFirstName": "Giles",
                    "guaGender": "Male",
                    "guaLastName": "Berge",
                    "guaNumber": "684-849-6569",
                    "relationship": "Aunty",
                },
                "account": {
                    "accountName": "9GET5GC7DM",
                    "accountBalance": 49835.01,
                    "loanRepayment": 30922.92,
                    "monthlyIncome": [63420.54, 2660261.11],
                    "bank": "Stanbic IBTC",
                    "accountNumber": 7774469151,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "nobis-molestias-ab",
                    "orgNumber": "918-969-6552",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Sarai_Kreiger@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae7",
                "profile": {
                    "firstName": "Garett",
                    "lastName": "Turner",
                    "phoneNumber": "(866) 952-8471",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/219.jpg",
                    "gender": "Male",
                    "bvn": "538905240",
                    "address": "Koss Port",
                    "currency": "NGN",
                    "email": "Jude.Sporer@hotmail.com",
                    "userName": "Filomena.Homenick45",
                    "status": "Inactive",
                },
                "guarantor": {
                    "guaAddress": "Vernice Plains",
                    "guaFirstName": "Anastacio",
                    "guaGender": "Male",
                    "guaLastName": "Sipes",
                    "guaNumber": "480-796-2088",
                    "relationship": "Aunty",
                },
                "account": {
                    "accountName": "0I4IRQXT1L",
                    "accountBalance": 55657.72,
                    "loanRepayment": 118275.6,
                    "monthlyIncome": [38762.34, 2195785.0],
                    "bank": "Access",
                    "accountNumber": 6447036308,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "illum-autem-voluptas",
                    "orgNumber": "655.385.6596",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Bernice.Feeney85@yahoo.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae8",
                "profile": {
                    "firstName": "Seamus",
                    "lastName": "Cole",
                    "phoneNumber": "207.629.3304 x484",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/26.jpg",
                    "gender": "Male",
                    "bvn": "278680207",
                    "address": "Rhoda Grove",
                    "currency": "NGN",
                    "email": "Giovani.Collins@hotmail.com",
                    "userName": "Hope_Fritsch18",
                    "status": "Blacklisted",
                },
                "guarantor": {
                    "guaAddress": "Kathleen Mews",
                    "guaFirstName": "Douglas",
                    "guaGender": "Male",
                    "guaLastName": "Gerhold",
                    "guaNumber": "(863) 949-1775 x2940",
                    "relationship": "Uncle",
                },
                "account": {
                    "accountName": "NT33OQSMHM",
                    "accountBalance": 20008.65,
                    "loanRepayment": 117478.36,
                    "monthlyIncome": [48453.2, 666607.27],
                    "bank": "Zenith",
                    "accountNumber": 3826000871,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "nihil-quae-fugit",
                    "orgNumber": "264-501-6220 x5745",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Llewellyn.Douglas73@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40ae9",
                "profile": {
                    "firstName": "Luigi",
                    "lastName": "Kessler",
                    "phoneNumber": "(244) 247-9696 x75867",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/297.jpg",
                    "gender": "Male",
                    "bvn": "797631216",
                    "address": "Brekke Ramp",
                    "currency": "NGN",
                    "email": "Roslyn28@gmail.com",
                    "userName": "Lionel_Stiedemann",
                    "status": "Blacklisted",
                },
                "guarantor": {
                    "guaAddress": "Antonietta Vista",
                    "guaFirstName": "Octavia",
                    "guaGender": "Male",
                    "guaLastName": "Sawayn",
                    "guaNumber": "273.241.7561 x0408",
                    "relationship": "Daughter",
                },
                "account": {
                    "accountName": "L2LJJ3SH0H",
                    "accountBalance": 22557.69,
                    "loanRepayment": 105557.02,
                    "monthlyIncome": [56111.75, 1551873.38],
                    "bank": "Access",
                    "accountNumber": 6433151781,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "ea-in-assumenda",
                    "orgNumber": "(498) 235-9750 x96022",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Reece74@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40aea",
                "profile": {
                    "firstName": "Joanie",
                    "lastName": "Ward",
                    "phoneNumber": "512-877-7284",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1064.jpg",
                    "gender": "Male",
                    "bvn": "704746660",
                    "address": "Bechtelar Rue",
                    "currency": "NGN",
                    "email": "Virgil_Walter86@gmail.com",
                    "userName": "Jovanny.Littel",
                    "status": "Blacklisted",
                },
                "guarantor": {
                    "guaAddress": "Feest Prairie",
                    "guaFirstName": "Gladyce",
                    "guaGender": "Male",
                    "guaLastName": "Ryan",
                    "guaNumber": "398.292.0898",
                    "relationship": "Sibling",
                },
                "account": {
                    "accountName": "7CQUXYAU7E",
                    "accountBalance": 26155.12,
                    "loanRepayment": 70586.92,
                    "monthlyIncome": [46008.53, 295872.61],
                    "bank": "Fidelity",
                    "accountNumber": 5180632995,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "in-expedita-quidem",
                    "orgNumber": "769-656-9012 x29833",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Stefan.Schoen@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
            {
                "_id": "65c7fe3ffe207b9decf40aeb",
                "profile": {
                    "firstName": "Anabel",
                    "lastName": "Bradtke",
                    "phoneNumber": "1-293-203-2521 x175",
                    "avatar": "https://cloudflare-ipfs.com/ipfs/Qmd3W5DuhgHirLHGVixi6V76LhCkZUz6pnFt5AJBiyvHye/avatar/1167.jpg",
                    "gender": "Male",
                    "bvn": "266779968",
                    "address": "Chanelle Tunnel",
                    "currency": "NGN",
                    "email": "Antonetta10@gmail.com",
                    "userName": "Jewel15",
                    "status": "Inactive",
                },
                "guarantor": {
                    "guaAddress": "Padberg Isle",
                    "guaFirstName": "Chandler",
                    "guaGender": "Male",
                    "guaLastName": "Roob",
                    "guaNumber": "327-608-8143",
                    "relationship": "Cousin",
                },
                "account": {
                    "accountName": "SO0YDCL6K5",
                    "accountBalance": 70822.05,
                    "loanRepayment": 58634.32,
                    "monthlyIncome": [40300.22, 894810.54],
                    "bank": "SunTrust",
                    "accountNumber": 1663361822,
                },
                "socials": {
                    "facebook": "@lendsqr",
                    "instagram": "@lendsqr",
                    "twitter": "@lendsqr",
                },
                "organization": {
                    "orgName": "ab-recusandae-qui",
                    "orgNumber": "1-667-400-3016 x933",
                    "employmentStatus": "Employed",
                    "sector": "FinTech",
                    "duration": "2 Years",
                    "officeEmail": "Cornelius_Langworth@gmail.com",
                },
                "education": {"level": "Bsc"},
            },
        ],
    }
]

print(body[0]["totalDocuments"])
